### ISSUE TITLE
Version 2.2

### ISSUE THREAD

**Issue by heruan** [mipmip/zabbix_agentd_osx_installer#1]
Can I compile this for Zabbix 2.2?

**Comment by tuxjobs** [comment]
have you tried it yet?

**Comment by bbrendon** [comment]
Can someone update this for 2.2?

**Comment by mipmip** [comment]
Hi, I'll try to make a new installer next week.

**Comment by frizull** [comment]
Voting for this one as well. Would be awesome !

**Comment by mipmip** [comment]
Check the release section for a fresh compiles 2.2.5 zabbix agent.
